// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProjectApp.Migrations.ProjectDB
{
    [DbContext(typeof(ProjectDBContext))]
    [Migration("20200922011146_AddJournalUpdateTrigger")]
    partial class AddJournalUpdateTrigger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ProjectApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("ProjectApp.Models.ChartData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChartUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChartUserId");

                    b.ToTable("ChartData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChartUserId = "93879f86-de21-4285-8b8f-2f76770859cc"
                        });
                });

            modelBuilder.Entity("ProjectApp.Models.ProjectViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDataId");

                    b.HasIndex("ProjectUserId");

                    b.HasIndex("ReportJournalId");

                    b.ToTable("ProjectViewModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2020, 9, 21, 20, 11, 46, 129, DateTimeKind.Local).AddTicks(3730),
                            Info = "test1",
                            Language = "Ruby",
                            Name = "Test1",
                            ProjectDataId = 1,
                            ProjectUserId = "93879f86-de21-4285-8b8f-2f76770859cc",
                            ReportJournalId = 1,
                            StartDate = new DateTime(2020, 9, 21, 20, 11, 46, 111, DateTimeKind.Local).AddTicks(8800)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2020, 9, 21, 20, 11, 46, 129, DateTimeKind.Local).AddTicks(5630),
                            Info = "test2",
                            Language = "React",
                            Name = "Test2",
                            ProjectDataId = 1,
                            ProjectUserId = "93879f86-de21-4285-8b8f-2f76770859cc",
                            ReportJournalId = 1,
                            StartDate = new DateTime(2020, 9, 21, 20, 11, 46, 129, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2020, 9, 21, 20, 11, 46, 129, DateTimeKind.Local).AddTicks(5680),
                            Info = "test2",
                            Language = "C#",
                            Name = "Test3",
                            ProjectDataId = 1,
                            ProjectUserId = "93879f86-de21-4285-8b8f-2f76770859cc",
                            ReportJournalId = 1,
                            StartDate = new DateTime(2020, 9, 21, 20, 11, 46, 129, DateTimeKind.Local).AddTicks(5670)
                        });
                });

            modelBuilder.Entity("ProjectApp.Models.ReportJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LanguageChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NameChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjLanguage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReportJournal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "JohnDoe",
                            ChangeCount = 0,
                            DevTime = 1,
                            LanguageChange = false,
                            NameChange = false,
                            ProjLanguage = "C#"
                        });
                });

            modelBuilder.Entity("ProjectApp.Models.ChartData", b =>
                {
                    b.HasOne("ProjectApp.Models.ApplicationUser", "ChartUser")
                        .WithMany("Charts")
                        .HasForeignKey("ChartUserId");
                });

            modelBuilder.Entity("ProjectApp.Models.ProjectViewModel", b =>
                {
                    b.HasOne("ProjectApp.Models.ChartData", "ProjectData")
                        .WithMany("DataForProjects")
                        .HasForeignKey("ProjectDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectApp.Models.ApplicationUser", "ProjectUser")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectUserId");

                    b.HasOne("ProjectApp.Models.ReportJournal", "Report")
                        .WithMany("Projects")
                        .HasForeignKey("ReportJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
